### ISSUE TITLE
spi nor acces problem

### ISSUE THREAD

**Issue by delscate** [libre-computer-project/libretech-u-boot#1]
There is spi nor read problem on last 2019.04/gxl comit  f9ca6fe : 

U-Boot 2019.04 (Oct 21 2019 - 15:24:34 +0200) Libre Computer AML-S805X-AC

Model: Libre Computer Board AML-S805X-AC
DRAM:  1 GiB
MMC:   mmc@74000: 0
Loading Environment from FAT... ** No device specified **
Loading Environment from SPI Flash... SF: Detected gd25lq128 with page size 256 Bytes, erase size 4 KiB, total 16 MiB
Cannot set mode (err=-19)
*** Warning - spi_flash_probe_bus_cs() failed, using default environment

log on last release : 

U-Boot 2019.04+ (Sep 09 2019 - 16:14:37 +0000) Libre Computer AML-S805X-AC

Model: Libre Computer Board AML-S805X-AC
DRAM:  1 GiB
MMC:   mmc@74000: 0
Loading Environment from SPI Flash... SF: Detected gd25lq128 with page size 256 Bytes, erase size 64 KiB, total 16 MiB
OK
In:    serial
Out:   serial
Err:   serial
Boot:  spi

**Comment by dsx724** [comment]
Please use the latest 2020.04 branch.
