### ISSUE TITLE
On roc-rk3399-pc uboot doesn't show anything on Dell UP3017

### ISSUE THREAD

**Issue by shvetsnikita** [libre-computer-project/libretech-u-boot#16]
Hello!

I found that uboot doesn't show anything (black screen instead of "no singal") on Dell UP3017, probably because this display have 2560x1600 resolution. [This image](https://distro.libre.computer/ci/debian/12/debian-12-base-arm64%2Broc-rk3399-pc.img.xz) was used for test (downloaded September 28).

**Comment by dsx724** [comment]
u-boot only initializes VOP little which is limited to 2560x1600 @ 60Hz. If your display has a higher refresh rate than 60, the target operating frequency will exceed the capabilities of the VOP little and not display anything.

**Comment by shvetsnikita** [comment]
Hello!

> If your display has a higher refresh rate than 60

It's 60 according to the [spec](https://i.dell.com/sites/csdocuments/Product_Docs/en/dell_ultrasharp_30_monitor_with_premiercolor_up3017_product_spec_sheet.pdf).
